services:
  init:
    image: "apache-doris:2.1.7-fe"
    hostname: "init"
    privileged: true
    entrypoint: 
      - bash
      - "-c"
      - |
        set -ex
        sysctl -w vm.max_map_count=2000000
    networks:
      doris_net:
        ipv4_address: 172.20.80.10
  fe:
    image: "apache-doris:2.1.7-fe"
    ulimits:
      nproc: 204800
      nofile:
        soft: 204800
        hard: 204800
    hostname: "fe"
    depends_on:
      - init
    environment:
      - FE_SERVERS=fe1:172.20.80.2:9010
      - FE_ID=1
    ports:
      - 8030:8030
      - 9030:9030
      - 9090:9090
    volumes:
      - ./data/fe/doris-meta:/opt/apache-doris/fe/doris-meta
      - ./data/fe/log:/opt/apache-doris/fe/log
    networks:
      doris_net:
        ipv4_address: 172.20.80.2
  be:
    image: "apache-doris:2.1.7-be"
    ulimits:
      nproc: 204800
      nofile:
        soft: 204800
        hard: 204800
    hostname: "be"
    depends_on:
      - fe
    environment:
      - FE_SERVERS=fe1:172.20.80.2:9010
      - BE_ADDR=172.20.80.3:9050
      - MASTER_FE_IP=172.20.80.2
      - CURRENT_BE_IP=172.20.80.3
      - CURRENT_BE_PORT=9050
      - PRIORITY_NETWORKS=172.20.80.0/24
    ports:
      - 8040:8040
    volumes:
      - ./data/be/storage:/opt/apache-doris/be/storage
      - ./data/be/script:/docker-entrypoint-initdb.d
      - ./data/be/log:/opt/apache-doris/be/log
    networks:
      doris_net:
        ipv4_address: 172.20.80.3
  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
      - 15432:15432
    environment:
      - CUBEJS_DEV_MODE=true
    volumes:
      - .:/cube/conf
    networks:
      doris_net:
        ipv4_address: 172.20.80.4
networks:
  doris_net:
    ipam:
      config:
        - subnet: 172.20.80.0/24