# 选择基础镜像
FROM openjdk:8u342-jdk

# 设置环境变量
ENV JAVA_HOME="/usr/local/openjdk-8/" 
ENV PATH="/opt/apache-doris/be/bin:$PATH"

# 下载软件至镜像内，可根据需要替换
ADD ./resource/apache-doris-2.1.7-bin-x64.tar.gz /opt/

RUN apt-get update && \
    apt-get install -y default-mysql-client && \
    apt-get clean && \
    mkdir /opt/apache-doris && \
    cd /opt && \
    mv apache-doris-2.1.7-bin-x64/be /opt/apache-doris/

ADD ./resource/init_be.sh /opt/apache-doris/be/bin
ADD ./resource/start_be.sh /opt/apache-doris/be/bin
RUN chmod 755 /opt/apache-doris/be/bin/init_be.sh
RUN chmod 755 /opt/apache-doris/be/bin/start_be.sh

RUN sed -i 's/arrow_flight_sql_port = -1/arrow_flight_sql_port = 9091/' /opt/apache-doris/be/conf/be.conf

ENTRYPOINT ["/opt/apache-doris/be/bin/init_be.sh"]